site_name: IT 快速使用指南
site_author: Vitan
nav: 
  - 入职使用指南: Guide/NewEmployee.md
  - 笔记本使用须知: Guide/Notebook.md
  - IT故障申报处理: Guide/ithelp.md
  - 计算机凭证管理: Guide/VoucherManagement.md
  - IT相关软件下载: Guide/Download.md
  - WLAN 无线网络设置: Guide/Wlan.md
  - Apple 笔记本安装虚拟机: Guide/Apple.md
  - 视频会议系统简易操作指南: Guide/VideoconferencingSystem.md
  - 视频会议移动终端操作手册: Guide/VideoconferencingMobile.md
  - 笔记本申购/借用/维修须知: Guide/BuyNotenook.md
  - 办公系统/资源账号密码及权限: Guide/Account.md
  - IE或Safari浏览器无法访问门户: Guide/MenHu.md

  - 邮箱事务:
    - 检查客户端是否使用POP连接类型: Guide/CheckPOP.md
    - 修改邮箱密码: Guide/ChangeMailPass.md
    - Windows Live Mail 设置: Guide/Windows_Live_Mail_Setting.md
    - Office Outlook 设置: Guide/OutlookSetting.md
    - Foxmail 设置: Guide/FoxMailSetting.md
    - Foxmail 数据备份: Guide/FoxMailBackup.md
    - McBook 数据备份: Guide/MacMailBackup.md
    - Outlook Express 数据备份: Guide/OutlookExpressBackup.md
    - Windows Live Mail 数据备份: Guide/LiveMailBackup.md
    - Live Mail 邮箱签名设置: Guide/LiveMailSignature.md
    - Live Mail 导入通讯录: Guide/LiveMailAddressBook.md
    - Outlook 导入通讯录: Guide/OutlookAddressBook.md
      
  - KM 一体机:
    - 网络打印机安装: Guide/PrnterInstall.md
    - 证件复印: Guide/PrintID.md
    - 传真功能: Guide/ChuanZhen.md
    - 传真平台: Guide/Czpt.md
    - 工卡注册流程: Guide/Card.md
    - 作业管理平台: Guide/KMWork.md
    - 打印输出报错: Guide/PrintErr.md
    - 彩色打印功能设置: Guide/ColorPrint.md

  - 办软件公系统安装视频:
    - SAP 安装教程: Guide/SAP.md
    - VSS 安装教程: Guide/VSS.md
    - MES 制造执行系统安装教程: Guide/MES.md
    - Windows Live Mail 邮件导出、导入: Guide/LiveMailOut.md

theme:
  name: null
  custom_dir: material/material
  language: 'zh'
  base_url: 'GRG_IT/docs/'
  logo: './imgs/logo.png'
  favicon: './imgs/fa.png'
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  features:
    - instant

  palette:
    primary: Blue
    accent: Blue

  font:
    text: Ubuntu
    code: Ubuntu Mono

plugins:
  - git-revision-date-localized:
      type: date
  - search:
      prebuild_index: true
      lang:
        - en
        - de
        - ru
        - ja
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite
  - admonition

extra_css:
    #- 'https://use.fontawesome.com/releases/v5.7.2/css/all.css'
    - 'assets/fontawesome/css/all.min.css'
    - 'assets/extra.css'

extra__js:
    - 'assets/css-vars-ponyfill.js'
